from abc import ABC, abstractmethod
from typing import Optional

class AIProvider(ABC):
    @abstractmethod
    async def extract_resume(self, text: str) -> dict: ...
    @abstractmethod
    async def generate_question(self, profile: dict, completeness: dict, previous: list[dict]) -> dict: ...
    @abstractmethod
    async def process_answer(self, profile: dict, question: dict, answer: str) -> dict: ...
    @abstractmethod
    async def recommend_roles(self, profile: dict, roles: list[dict]) -> list[dict]: ...
    @abstractmethod
    async def analyze_resume(self, profile: dict, original: str) -> dict: ...
    @abstractmethod
    async def rewrite_resume(self, profile: dict, original: str, target_role: Optional[str]) -> str: ...
