import { useCallback, useEffect, useMemo, useState } from 'react';
import { ApiError, endpoints, session } from './api';

const NAV = [
  ['dashboard', 'Overview'], ['resume', 'Resume'], ['profile', 'Profile'], ['interview', 'AI interview'], ['matches', 'Role matches'],
  ['search', 'Job search'], ['opportunities', 'Opportunities'], ['applications', 'Applications'], ['outreach', 'Outreach'], ['gmail', 'Gmail'], ['settings', 'Settings'],
];

const identity = (value) => value?.user || value?.account || value?.data?.user || value?.data?.account || value || {};
const rows = (value) => {
  if (Array.isArray(value)) return value;
  const data = value?.data || value || {};
  return data.items || data.results || data.opportunities || data.recommendations || data.roles || data.applications || data.outreach || data.saved_jobs || data.searches || [];
};
const profileData = (value) => value?.profile || value?.data?.profile || value?.data || value || {};
const completenessData = (value) => value?.completeness || value?.data?.completeness || value?.data || value || {};
const displayName = (user) => { const person = identity(user); return person.display_name || person.name || person.email?.split('@')[0] || 'there'; };
const userId = (user) => { const person = identity(user); return person.id || person.user_id; };
const errorText = (error) => error instanceof ApiError ? error.message : 'Something went wrong. Please try again.';

function useHashRoute() {
  const getRoute = () => location.hash.replace('#/', '').split('?')[0] || 'dashboard';
  const [route, setRoute] = useState(getRoute);
  useEffect(() => { const update = () => setRoute(getRoute()); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update); }, []);
  const navigate = (next) => { location.hash = `#/${next}`; };
  return [route, navigate];
}

function Notice({ notice, onClose }) { return notice ? <div className={`notice ${notice.kind || 'info'}`} role="status">{notice.text}<button onClick={onClose} aria-label="Dismiss message">×</button></div> : null; }
function Loading({ label = 'Loading…' }) { return <div className="loading"><span />{label}</div>; }
function Empty({ title, copy, action }) { return <section className="empty"><div className="empty-icon">✦</div><h2>{title}</h2><p>{copy}</p>{action}</section>; }
function Score({ value = 0 }) { return <div className="score" style={{ '--score': `${Math.max(0, Math.min(100, Number(value) || 0))}%` }}><strong>{Math.round(Number(value) || 0)}</strong><span>fit</span></div>; }
function Card({ children, className = '' }) { return <section className={`card ${className}`}>{children}</section>; }
function Button({ children, className = '', ...props }) { return <button className={`button ${className}`} {...props}>{children}</button>; }

function Auth({ onAuthenticated, notify }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ display_name: '', email: '', password: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event) => {
    event.preventDefault(); setBusy(true); setError('');
    try {
      const data = mode === 'register' ? await endpoints.register(form) : await endpoints.login({ email: form.email, password: form.password });
      session.set(data); const me = identity(data.user || await endpoints.me()); onAuthenticated(me); notify('Welcome to Chably.', 'success');
    } catch (err) { setError(errorText(err)); } finally { setBusy(false); }
  };
  const signInWithGoogle = async () => { setBusy(true); setError(''); try { const data = await endpoints.googleLogin(); window.location.assign(data.authorization_url); } catch (err) { setError(errorText(err)); setBusy(false); } };
  return <main className="auth-page"><section className="auth-intro"><a className="brand" href="#/">c<span>chably</span></a><p className="eyebrow">CAREER INTELLIGENCE, WITHOUT THE NOISE</p><h1>Make your next move <em>make sense.</em></h1><p>Turn your experience into a clear profile, better-fit roles and thoughtful outreach.</p></section><section className="auth-form"><div className="auth-panel"><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'START WITH YOUR SIGNAL'}</p><h2>{mode === 'login' ? 'Pick up where you left off.' : 'Create your workspace.'}</h2><p className="muted">Sign in with email or Google. Gmail permissions are requested later, separately.</p>{error && <p className="form-error">{error}</p>}<Button className="google-button" type="button" disabled={busy} onClick={signInWithGoogle}><span>G</span> Continue with Google</Button><div className="auth-divider"><span>or</span></div><form onSubmit={submit}>{mode === 'register' && <label>Name<input value={form.display_name} onChange={(e) => setForm({ ...form, display_name: e.target.value })} maxLength="256" placeholder="Your name" /></label>}<label>Email<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input type="password" required minLength={mode === 'register' ? 10 : 1} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder={mode === 'register' ? 'At least 10 characters' : 'Your password'} /></label><Button disabled={busy}>{busy ? 'Working…' : mode === 'login' ? 'Sign in to Chably' : 'Create my workspace'} →</Button></form><p className="switch">{mode === 'login' ? 'New to Chably?' : 'Already have an account?'} <button onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></div></section></main>;
}

function GoogleCallback({ onAuthenticated, notify }) {
  const [error, setError] = useState('');
  useEffect(() => { const code = new URLSearchParams(location.hash.split('?')[1] || '').get('code'); if (!code) { setError('Google sign-in did not return a valid code.'); return; } endpoints.googleExchange(code).then((data) => { session.set(data); onAuthenticated(identity(data.user)); notify('Signed in with Google.', 'success'); location.hash = '#/dashboard'; }).catch((err) => setError(errorText(err))); }, [onAuthenticated, notify]);
  return error ? <main className="callback-page"><Empty title="Google sign-in unavailable" copy={error} action={<Button onClick={() => { location.hash = '#/login'; }}>Back to sign in</Button>} /></main> : <Loading label="Finishing your secure Google sign-in…" />;
}

function Shell({ user, route, navigate, children, onLogout }) {
  const [open, setOpen] = useState(false);
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><a className="brand" href="#/dashboard">c<span>chably</span></a><nav>{NAV.map(([id, label]) => <button className={route === id ? 'active' : ''} key={id} onClick={() => { navigate(id); setOpen(false); }}>{label}</button>)}</nav><div className="sidebar-user"><span>{displayName(user).slice(0, 2).toUpperCase()}</span><div><strong>{displayName(user)}</strong><button onClick={onLogout}>Sign out</button></div></div></aside><div className="scrim" onClick={() => setOpen(false)} /><main className="workspace"><header><button className="menu" onClick={() => setOpen(true)} aria-label="Open navigation">☰</button><p>One clear move at a time.</p><span className="avatar">{displayName(user).slice(0, 2).toUpperCase()}</span></header>{children}</main></div>;
}

function PageHead({ eyebrow, title, copy, action }) { return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy && <p>{copy}</p>}</div>{action}</div>; }

function Dashboard({ user, navigate }) {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { endpoints.dashboard().then(setData).catch((err) => setError(errorText(err))); }, []);
  if (error) return <Empty title="Dashboard unavailable" copy={error} />;
  if (!data) return <Loading label="Loading your career workspace…" />;
  const profile = data.profile || {}; const completeness = data.completeness?.overall_score || data.completeness?.percentage || profile.completeness || 0; const opportunities = rows(data.recent_opportunities); const applications = data.application_counts || data.applications || {};
  return <><PageHead eyebrow="YOUR CAREER WORKSPACE" title={`Good to see you, ${displayName(user)}.`} copy="Use your profile, evidence and opportunities to make the next move more intentional." action={<Button onClick={() => navigate('search')}>Find roles →</Button>} /><div className="dashboard-grid"><Card className="next-move"><p className="eyebrow">YOUR NEXT BEST MOVE</p><h2>{data.next_action?.title || 'Complete your profile before you widen the search.'}</h2><p>{data.next_action?.message || 'A stronger profile creates more useful role matches and outreach.'}</p><Button onClick={() => navigate('interview')}>Continue interview →</Button><div className="completion"><strong>{Math.round(completeness)}%</strong><span>profile complete</span></div></Card><Card><p className="eyebrow">GOOGLE CONNECTION</p><h2>{data.google_connection?.connected ? 'Gmail is connected' : 'Connect Gmail when you are ready'}</h2><p className="muted">Outreach always remains approval-first.</p><Button className="secondary" onClick={() => navigate('gmail')}>{data.google_connection?.connected ? 'View Gmail' : 'Connect Gmail'}</Button></Card></div><div className="metrics"><Metric label="Role matches" value={rows(data.recommendations).length || '—'} /><Metric label="Opportunities" value={opportunities.length || '—'} /><Metric label="Applications" value={typeof applications === 'object' ? Object.values(applications).reduce((a, b) => a + (Number(b) || 0), 0) || '—' : applications || '—'} /></div><Card><div className="section-title"><div><p className="eyebrow">RECENT OPPORTUNITIES</p><h2>Worth a closer look</h2></div><Button className="text-button" onClick={() => navigate('opportunities')}>View all</Button></div>{opportunities.length ? <OpportunityList items={opportunities.slice(0, 3)} /> : <p className="muted">Run a job search to see opportunities here.</p>}</Card></>;
}
function Metric({ label, value }) { return <Card className="metric"><p>{label}</p><strong>{value}</strong></Card>; }

function Resume({ user, notify }) {
  const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [result, setResult] = useState(null); const [analysis, setAnalysis] = useState(null); const [error, setError] = useState('');
  const upload = async () => { if (!file || file.type !== 'application/pdf') return setError('Choose a PDF resume.'); setBusy(true); setError(''); try { const data = await endpoints.uploadResume(file); setResult(data); notify('Resume uploaded and processed.', 'success'); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  const analyze = async () => { setBusy(true); try { setAnalysis(await endpoints.resumeAnalysis(userId(user))); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  return <><PageHead eyebrow="YOUR FOUNDATION" title="Resume review" copy="Upload a PDF and let Chably turn it into evidence you can refine." /><div className="two-col"><Card><h2>Upload your resume</h2><p className="muted">PDF only, up to the backend’s configured size limit.</p><label className="dropzone"><input type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] || null)} /><strong>{file ? file.name : 'Choose a PDF file'}</strong><span>{file ? `${Math.round(file.size / 1024)} KB selected` : 'Your file stays with your Chably account.'}</span></label>{error && <p className="form-error">{error}</p>}<Button disabled={!file || busy} onClick={upload}>{busy ? 'Processing…' : 'Upload and process'}</Button></Card><Card><p className="eyebrow">RESUME INTELLIGENCE</p><h2>{result ? 'Resume processed' : 'What Chably will do'}</h2><p>{result?.message || 'Extract structured profile information, identify evidence and use it to support role matches.'}</p><Button className="secondary" disabled={busy || !userId(user)} onClick={analyze}>{busy ? 'Analyzing…' : 'Analyze my resume'}</Button>{analysis && <pre className="result">{JSON.stringify(analysis, null, 2)}</pre>}</Card></div></>;
}

function Profile({ notify }) {
  const [profile, setProfile] = useState(null); const [draft, setDraft] = useState(''); const [complete, setComplete] = useState(null); const [editing, setEditing] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([endpoints.profile(), endpoints.completeness()]).then(([p, c]) => { const normalized = profileData(p); setProfile(normalized); setDraft(JSON.stringify(normalized, null, 2)); setComplete(completenessData(c)); }).catch((err) => setError(errorText(err))); }, []);
  const save = async () => { try { setBusy(true); const saved = await endpoints.profilePatch(JSON.parse(draft)); const normalized = profileData(saved); setProfile(normalized); setDraft(JSON.stringify(normalized, null, 2)); setComplete(completenessData(saved)); setEditing(false); notify('Profile saved.', 'success'); } catch (err) { setError(err instanceof SyntaxError ? 'Profile data must be valid JSON.' : errorText(err)); } finally { setBusy(false); } };
  if (!profile && !error) return <Loading label="Loading your profile…" />;
  const identityInfo = profile.identity || {}; const skills = Object.values(profile.skills || {}).flat().filter(Boolean); const categories = complete.categories || [];
  return <><PageHead eyebrow="YOUR SIGNAL" title="Profile and completeness" copy="Your resume-derived profile, organized for review." action={<div className="actions"><Button className="secondary" onClick={() => setEditing(!editing)}>{editing ? 'Close editor' : 'Edit profile'}</Button>{editing && <Button onClick={save} disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</Button>}</div>} />{error && <p className="form-error">{error}</p>}<div className="profile-layout"><div className="profile-main"><Card className="profile-hero"><div><p className="eyebrow">CANDIDATE PROFILE</p><h2>{identityInfo.name || 'Your career profile'}</h2><p>{identityInfo.location || 'Location not added'}{identityInfo.email ? ` · ${identityInfo.email}` : ''}</p></div>{profile.professional_summary && <p className="summary">{profile.professional_summary}</p>}</Card><Card><p className="eyebrow">EXPERIENCE</p>{profile.experience?.length ? <div className="timeline">{profile.experience.map((item, index) => <div key={index}><h3>{item.title || item.role || 'Role'}{item.company ? ` · ${item.company}` : ''}</h3><p>{item.start_date || item.start || ''}{item.end_date || item.end ? ` — ${item.end_date || item.end}` : ''}</p><p>{item.description || item.summary || ''}</p></div>)}</div> : <p className="muted">No experience entries have been extracted yet.</p>}</Card><Card><p className="eyebrow">PROJECTS</p>{profile.projects?.length ? <div className="timeline">{profile.projects.map((item, index) => <div key={index}><h3>{item.name || item.title || 'Project'}</h3><p>{item.description || item.summary || ''}</p></div>)}</div> : <p className="muted">No projects have been extracted yet.</p>}</Card>{editing && <Card><h2>Advanced profile editor</h2><p className="muted">Edit the structured data only when it accurately reflects your experience.</p><textarea className="json-editor" value={draft} onChange={(e) => setDraft(e.target.value)} aria-label="Candidate profile JSON" /></Card>}</div><aside className="profile-side"><Card><p className="eyebrow">COMPLETENESS</p><strong className="profile-score">{complete.overall ?? complete.overall_score ?? complete.percentage ?? 0}%</strong><p className="muted">Profile strength improves recommendations and outreach.</p><div className="category-list">{categories.map((category, index) => <div key={category.name || index}><span>{category.label || category.name || 'Profile detail'}</span><strong>{category.score ?? category.percentage ?? 0}%</strong></div>)}</div></Card><Card><p className="eyebrow">SKILLS</p><div className="chips">{skills.length ? skills.slice(0, 24).map((skill, index) => <span key={`${skill}-${index}`}>{skill}</span>) : <p className="muted">Skills will appear after your resume is processed.</p>}</div></Card></aside></div></>;
}

function Interview({ user, notify }) {
  const [question, setQuestion] = useState(null); const [history, setHistory] = useState([]); const [answer, setAnswer] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const id = userId(user);
  const load = useCallback(async () => { if (!id) return; try { const [next, previous] = await Promise.all([endpoints.interviewStart(id), endpoints.interviewHistory(id)]); setQuestion(next); setHistory(rows(previous)); } catch (err) { setError(errorText(err)); } }, [id]);
  useEffect(() => { load(); }, [load]);
  const submit = async (event) => { event.preventDefault(); if (!question?.question_id || !answer.trim()) return; setBusy(true); try { const next = await endpoints.interviewAnswer(id, { question_id: question.question_id, answer }); setQuestion(next); setAnswer(''); setHistory((items) => [...items, { question: question.question || question.text, answer }]); notify('Answer saved.', 'success'); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  return <><PageHead eyebrow="ADAPTIVE INTERVIEW" title="Build a sharper picture" copy="One honest answer at a time. Chably uses your evidence to strengthen the profile." />{error && <p className="form-error">{error}</p>}<Card className="interview">{history.map((item, index) => <div className="message" key={index}><strong>Chably</strong><p>{item.question || item.question_text}</p>{item.answer && <><strong>You</strong><p>{item.answer}</p></>}</div>)}{question ? <><div className="message current"><strong>Chably</strong><p>{question.question || question.text || 'What would you like to add to your career story?'}</p></div><form onSubmit={submit}><textarea value={answer} onChange={(e) => setAnswer(e.target.value)} maxLength="5000" placeholder="Write an honest, specific answer…" /><Button disabled={busy || !answer.trim()}>{busy ? 'Saving…' : 'Send answer →'}</Button></form></> : <Loading label="Preparing your next question…" />}</Card></>;
}

function Matches({ user }) { const [items, setItems] = useState(null); const [error, setError] = useState(''); useEffect(() => { endpoints.recommendations(userId(user)).then((data) => setItems(rows(data))).catch((err) => setError(errorText(err))); }, [user]); return <><PageHead eyebrow="ROLE INTELLIGENCE" title="Roles with a reason" copy="Recommendations grounded in the profile you have built." />{error ? <Empty title="Recommendations unavailable" copy={error} /> : !items ? <Loading label="Finding role matches…" /> : items.length ? <OpportunityList items={items} /> : <Empty title="No recommendations yet" copy="Upload a resume and complete more of your profile to generate recommendations." />}</>; }

function Search({ user, navigate }) {
  const [query, setQuery] = useState(''); const [search, setSearch] = useState(null); const [progress, setProgress] = useState(null); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!search?.id && !search?.search_id) return; const id = search.id || search.search_id; let active = true; const poll = async () => { try { const update = await endpoints.searchProgress(id); if (!active) return; setProgress(update); const status = update.status || update?.progress?.status; if (['completed', 'failed'].includes(status)) { setResult(await endpoints.searchResults(id)); return; } setTimeout(poll, 2000); } catch (err) { if (active) setError(errorText(err)); } }; poll(); return () => { active = false; }; }, [search]);
  const submit = async (event) => { event.preventDefault(); if (query.trim().length < 3) return setError('Describe the roles you want in at least three characters.'); setBusy(true); setError(''); try { const data = await endpoints.search({ user_id: userId(user), query }); setSearch(data); setProgress(data); navigate('search'); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  const found = rows(result?.opportunities || result?.results || result);
  return <><PageHead eyebrow="SEARCH, IN YOUR WORDS" title="What would feel like a good next chapter?" copy="Chably turns a natural-language request into a focused, explainable opportunity set." /><Card className="search-box"><form onSubmit={submit}><textarea value={query} onChange={(e) => setQuery(e.target.value)} placeholder="For example: Backend and applied AI roles in Bangalore for 0–3 years experience" /><Button disabled={busy}>{busy ? 'Starting search…' : 'Search with intent →'}</Button></form>{error && <p className="form-error">{error}</p>}</Card>{progress && <Card><p className="eyebrow">SEARCH PROGRESS</p><h2>{progress.status || 'Searching'}</h2><pre className="result">{JSON.stringify(progress.progress || progress, null, 2)}</pre></Card>}{found.length ? <><h2 className="list-heading">Search results</h2><OpportunityList items={found} /></> : search && !error ? <Loading label="Searching real sources…" /> : null}</>;
}

function OpportunityList({ items }) { return <div className="opportunity-list">{items.map((item, index) => { const job = item.job || item; const company = item.company || {}; const title = job.title || job.raw_title || item.title || 'Opportunity'; const score = item.final_fit_score ?? item.fit_score ?? item.analysis?.fit_score; return <Card className="opportunity" key={item.id || job.id || index}><Score value={score} /><div><p className="eyebrow">{item.status || item.fit_level || 'OPPORTUNITY'}</p><h2>{title}</h2><p>{company.name || job.company_name || item.company_name || 'Company'} · {job.location || item.location || 'Location not listed'}{job.remote_type ? ` · ${job.remote_type}` : ''}</p><div className="chips">{(job.skills || item.matched_skills || []).slice(0, 6).map((skill) => <span key={skill}>{skill}</span>)}</div></div>{job.job_url && <a className="external" href={job.job_url} target="_blank" rel="noreferrer">View job ↗</a>}</Card>; })}</div>; }

function Opportunities({ user, type = 'all' }) { const [items, setItems] = useState(null); const [error, setError] = useState(''); useEffect(() => { (type === 'saved' ? endpoints.savedJobs() : endpoints.opportunities()).then((data) => setItems(rows(data))).catch((err) => setError(errorText(err))); }, [type, user]); return <><PageHead eyebrow={type === 'saved' ? 'YOUR SHORTLIST' : 'OPPORTUNITY SET'} title={type === 'saved' ? 'Saved jobs' : 'Opportunities'} copy="Review fit before you apply or reach out." />{error ? <Empty title="Opportunities unavailable" copy={error} /> : !items ? <Loading /> : items.length ? <OpportunityList items={items} /> : <Empty title="Nothing here yet" copy="Run a job search to create your first opportunity set." />}</>; }

function Applications({ user, notify }) { const [items, setItems] = useState(null); const [error, setError] = useState(''); const load = () => endpoints.applications().then((data) => setItems(rows(data))).catch((err) => setError(errorText(err))); useEffect(load, []); const update = async (item, status) => { try { await endpoints.updateApplication(item.id, userId(user), { status, notes: item.notes || '' }); notify('Application updated.', 'success'); load(); } catch (err) { notify(errorText(err), 'error'); } }; return <><PageHead eyebrow="MOMENTUM" title="Applications" copy="Keep your real application progress in one place." />{error ? <Empty title="Applications unavailable" copy={error} /> : !items ? <Loading /> : items.length ? <div className="application-list">{items.map((item) => <Card className="application" key={item.id}><div><h2>{item.job?.title || item.role || 'Application'}</h2><p>{item.company?.name || item.company_name || ''}</p></div><select value={item.status || 'applied'} onChange={(e) => update(item, e.target.value)} aria-label="Application status"><option value="saved">Saved</option><option value="applied">Applied</option><option value="replied">Replied</option><option value="interview">Interview</option><option value="rejected">Rejected</option></select></Card>)}</div> : <Empty title="No applications yet" copy="Create applications from an opportunity after you decide to apply." />}</>; }

function Outreach({ user, notify }) { const [items, setItems] = useState(null); const [error, setError] = useState(''); const load = () => endpoints.outreach().then((data) => setItems(rows(data))).catch((err) => setError(errorText(err))); useEffect(load, []); const run = async (method, item) => { if (method === 'send' && !confirm('Send this approved outreach email through Gmail?')) return; try { await (method === 'send' ? endpoints.sendOutreach(item.id, userId(user)) : endpoints.approveOutreach(item.id, userId(user))); notify(method === 'send' ? 'Outreach sent.' : 'Outreach approved.', 'success'); load(); } catch (err) { notify(errorText(err), 'error'); } }; return <><PageHead eyebrow="APPROVAL-FIRST OUTREACH" title="Outreach drafts" copy="Review each message before approval and sending." />{error ? <Empty title="Outreach unavailable" copy={error} /> : !items ? <Loading /> : items.length ? <div className="outreach-list">{items.map((item) => <Card key={item.id}><p className="eyebrow">{item.status || 'DRAFT'}</p><h2>{item.subject || 'Outreach draft'}</h2><p className="draft-body">{item.body || 'No message body returned.'}</p><div className="actions">{item.status === 'draft' && <Button className="secondary" onClick={() => run('approve', item)}>Approve draft</Button>}{item.status === 'approved' && <Button onClick={() => run('send', item)}>Send via Gmail</Button>}</div></Card>)}</div> : <Empty title="No outreach drafts" copy="Discover a contact from an opportunity, then create a draft to review here." />}</>; }

function Gmail({ user, notify }) { const [status, setStatus] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const load = () => endpoints.googleStatus().then(setStatus).catch((err) => setError(errorText(err))); useEffect(load, []); const connect = async () => { setBusy(true); try { const data = await endpoints.googleConnect(); window.open(data.authorization_url, 'chably-google-oauth', 'popup,width=520,height=720'); notify('Finish Google authorization in the popup, then refresh this status.', 'info'); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }; const sync = async () => { setBusy(true); try { const result = await endpoints.googleSync(userId(user)); notify(`Sync finished: ${result.new_replies ?? result.messages_processed ?? 0} new replies.`, 'success'); load(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }; return <><PageHead eyebrow="YOUR CONNECTION" title="Gmail" copy="Gmail authorization is separate from Chably login. Tokens remain encrypted in the backend." />{error && <p className="form-error">{error}</p>}<Card className="gmail-card">{!status ? <Loading /> : <><p className="eyebrow">{status.connected ? 'CONNECTED' : 'NOT CONNECTED'}</p><h2>{status.connected ? status.email || 'Google account connected' : 'Connect Gmail when you are ready'}</h2><p>{status.connected ? 'Reply tracking and approval-first sends are available.' : 'Chably asks only for Gmail send and readonly scopes required for outreach and reply tracking.'}</p><div className="actions">{status.connected ? <Button disabled={busy} onClick={sync}>{busy ? 'Syncing…' : 'Sync replies'}</Button> : <Button disabled={busy} onClick={connect}>{busy ? 'Opening Google…' : 'Connect Gmail'}</Button>}<Button className="secondary" onClick={load}>Refresh status</Button></div></>}</Card></>;
}

function Settings({ notify }) { const [settings, setSettings] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { endpoints.settings().then(setSettings).catch((err) => setError(errorText(err))); }, []); const update = async (event) => { event.preventDefault(); setBusy(true); try { await endpoints.patchSettings(settings || {}); notify('Settings saved.', 'success'); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }; const exportData = async () => { try { const data = await endpoints.accountExport(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'chably-account-export.json'; link.click(); URL.revokeObjectURL(url); } catch (err) { setError(errorText(err)); } }; const deleteAccount = async () => { if (!confirm('Delete your Chably account and user-owned data? This cannot be undone.')) return; try { await endpoints.deleteAccount(); session.clear(); location.hash = '#/login'; location.reload(); } catch (err) { setError(errorText(err)); } }; return <><PageHead eyebrow="WORKSPACE CONTROLS" title="Settings and privacy" copy="Automatic replies are disabled by default and should remain an explicit decision." />{error && <p className="form-error">{error}</p>}<div className="two-col"><Card><h2>Career and outreach settings</h2><p className="muted">The JSON reflects the server’s settings schema.</p><form onSubmit={update}><textarea className="json-editor" value={JSON.stringify(settings || {}, null, 2)} onChange={(e) => { try { setSettings(JSON.parse(e.target.value)); setError(''); } catch { setError('Settings must be valid JSON.'); } }} /><Button disabled={busy}>{busy ? 'Saving…' : 'Save settings'}</Button></form></Card><Card><h2>Account data</h2><p className="muted">Export excludes password hashes and OAuth credentials.</p><div className="actions"><Button className="secondary" onClick={exportData}>Download my data</Button><Button className="danger" onClick={deleteAccount}>Delete account</Button></div></Card></div></>;
}

export default function App() {
  const [route, navigate] = useHashRoute(); const [user, setUser] = useState(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(null);
  const notify = (text, kind = 'info') => setNotice({ text, kind });
  useEffect(() => { if (!session.refreshToken) { setLoading(false); return; } endpoints.me().then((data) => setUser(identity(data))).catch(() => session.clear()).finally(() => setLoading(false)); }, []);
  const logout = async () => { try { await endpoints.logout(); } catch {} session.clear(); setUser(null); navigate('login'); };
  const page = useMemo(() => ({ dashboard: <Dashboard user={user} navigate={navigate} />, resume: <Resume user={user} notify={notify} />, profile: <Profile notify={notify} />, interview: <Interview user={user} notify={notify} />, matches: <Matches user={user} />, search: <Search user={user} navigate={navigate} />, opportunities: <Opportunities user={user} />, applications: <Applications user={user} notify={notify} />, outreach: <Outreach user={user} notify={notify} />, gmail: <Gmail user={user} notify={notify} />, settings: <Settings notify={notify} /> }[route] || <Dashboard user={user} navigate={navigate} />), [route, user]);
  if (loading) return <Loading label="Restoring your Chably session…" />;
  if (!user) return <><Notice notice={notice} onClose={() => setNotice(null)} />{route === 'oauth/callback' ? <GoogleCallback onAuthenticated={setUser} notify={notify} /> : <Auth onAuthenticated={setUser} notify={notify} />}</>;
  return <><Notice notice={notice} onClose={() => setNotice(null)} /><Shell user={user} route={route} navigate={navigate} onLogout={logout}>{page}</Shell></>;
}
